-- Shopper schema: catalog + per-user cart / wishlist / orders + reviews.
-- Per-user data is scoped by auth.uid(); the frontend uses Supabase anonymous
-- sign-in so every visitor gets an identity without a login screen.
-- NOTE: enable "Anonymous sign-ins" in Authentication > Sign In / Providers.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.products (
  id           integer generated by default as identity primary key,
  name         text    not null,
  category     text    not null,
  price        numeric not null,
  orig_price   numeric,
  image        text,
  rating       numeric not null default 0,
  sold         integer not null default 0,
  stock        integer not null default 0,
  badge        text,
  max_per_user integer,
  description  text,
  video        text,
  variants     jsonb,
  images       jsonb,
  qa           jsonb,
  seller       jsonb,
  created_at   timestamptz not null default now()
);

create table if not exists public.reviews (
  id          bigint generated by default as identity primary key,
  product_id  integer not null references public.products(id) on delete cascade,
  user_name   text    not null,
  rating      integer not null check (rating between 1 and 5),
  comment     text    not null,
  review_date date    not null default current_date,
  user_id     uuid    references auth.users(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index if not exists reviews_product_id_idx on public.reviews(product_id);

create table if not exists public.orders (
  id         bigint  generated by default as identity primary key,
  user_id    uuid    not null references auth.users(id) on delete cascade,
  items      jsonb   not null,
  total      numeric not null,
  status     text    not null default 'Processing',
  cancelled  boolean not null default false,
  shipping   jsonb,
  delivery   text,
  rated      integer,
  created_at timestamptz not null default now()
);
create index if not exists orders_user_id_idx on public.orders(user_id);

create table if not exists public.wishlist (
  user_id    uuid    not null references auth.users(id) on delete cascade,
  product_id integer not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.cart (
  user_id    uuid    not null references auth.users(id) on delete cascade,
  product_id integer not null references public.products(id) on delete cascade,
  qty        integer not null check (qty > 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.products enable row level security;
alter table public.reviews  enable row level security;
alter table public.orders   enable row level security;
alter table public.wishlist enable row level security;
alter table public.cart     enable row level security;

-- Catalog + reviews are public read.
drop policy if exists "products read" on public.products;
create policy "products read" on public.products
  for select using (true);

drop policy if exists "reviews read" on public.reviews;
create policy "reviews read" on public.reviews
  for select using (true);

-- Any signed-in visitor (incl. anonymous) can post a review.
drop policy if exists "reviews insert" on public.reviews;
create policy "reviews insert" on public.reviews
  for insert to authenticated with check (true);

-- Orders / wishlist / cart: each visitor only sees and edits their own rows.
drop policy if exists "orders owner" on public.orders;
create policy "orders owner" on public.orders
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "wishlist owner" on public.wishlist;
create policy "wishlist owner" on public.wishlist
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "cart owner" on public.cart;
create policy "cart owner" on public.cart
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
